# Generated by Django 3.2.7 on 2023-04-25 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='total_like',
        ),
    ]
